[package]
name = "parser_v2"
version = "0.1.0"
edition = "2018"

[dependencies]
gramatika = "*"

[dev-dependencies]
criterion = "0.3"
parser = { path = "../parser" }

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "traversal"
harness = false
