[package]
name = "parser_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "*"
lazy_static = "*"
lsp-types = "0.91"
parking_lot = "0.11"

[dependencies.gramatika]
git = "https://github.com/dannymcgee/gramatika.git"
branch = "main"

[dev-dependencies]
parser = { path = "../parser" }
similar = "2.1"
utils = { path = "../utils" }

[dev-dependencies.criterion]
version = "0.3"
features = ["cargo_bench_support", "html_reports"]

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "traversal"
harness = false

[[bench]]
name = "scopes"
harness = false
