# Forked from https://github.com/gfx-rs/naga
[package]
name = "naga"
version = "0.5.0"
authors = ["Naga Developers"]
edition = "2018"

[dependencies]
bitflags = "1"
bit-set = "0.5"
codespan-reporting = { version = "0.11.0", optional = true }
fxhash = "0.2"
log = "0.4"
num-traits = "0.2"
spirv = { package = "spirv_headers", version = "1.5", optional = true }
thiserror = "1.0.21"
serde = { version = "1.0", features = ["derive"], optional = true }
petgraph = { version ="0.5", optional = true }
rose_tree = { version ="0.2", optional = true }
pp-rs = { version = "0.2.1", optional = true }

[features]
default = []
dot-out = []
glsl-in = ["pp-rs"]
glsl-validate = []
glsl-out = ["petgraph"]
msl-out = []
serialize = ["serde"]
deserialize = ["serde"]
spv-in = ["petgraph", "spirv", "rose_tree"]
spv-out = ["spirv"]
wgsl-in = ["codespan-reporting"]
wgsl-out = []
hlsl-out = []

[dev-dependencies]
diff = "0.1"
ron = "0.6"
serde = { version = "1.0", features = ["derive"] }
spirv = { package = "spirv_headers", version = "1.5", features = ["deserialize"] }
rspirv = "0.7"
