[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
crossbeam = "0.8"
dashmap = "4"
itertools = "0.10"
lazy_static = "1.4"
lsp-server = "0.5"
lsp-types = "0.91"
parking_lot = "0.11"
parser = { path = "../parser" }
parser_v2 = { path = "../parser_v2" }
pest = "*"
rand = "0.8"
ropey = "1.5"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
wgsl_plus = { path = "../wgsl-plus" }

[dependencies.gramatika]
git = "https://github.com/dannymcgee/gramatika.git"
branch = "main"

[dependencies.naga]
version = "0.12"
features = ["span", "validate", "wgsl-in"]
