[package]
name = "server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-server = "0.5"
lsp-types = "0.89"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
