[package]
name = "wgsl_plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
lsp-types = "0.91"
parser = { path = "../parser" }
